version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: vscode.Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=qwerty #optional
      - SUDO_PASSWORD_HASH=qwerty #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE= #optional
    volumes:
      - ./config:/config/
    ports:
      - 82:8443
      - 81:80
    restart: unless-stopped

  mysql:
    build:
      context: .
      dockerfile: database.Dockerfile
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: beeyev/phpmyadmin-lightweight:latest
    restart: unless-stopped
    tty: true
    environment:
      - 'TZ=CET'
      - 'PMA_HOST=mysql'
      - 'PMA_USER=root'
      - 'PMA_PASSWORD=qwerty'
    ports:
      - '83:80'