version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: vscode.Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=qwerty #optional
      - SUDO_PASSWORD_HASH=qwerty #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE= #optional
    restart: always
    volumes:
      - ./config:/config/
    ports:
      - 81:8443
      - 80:80
      
  mysql:
    build:
      context: .
      dockerfile: database.Dockerfile
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 82:80
    environment:
      - PMA_ARBITRARY=1
